import type { TechItem } from "./types";

/** Catalog covering software, QA, DevOps, AI agents, data, design, HR, and marketing. */
export const TECH_CATEGORIES: Record<string, [string, string][]> = {
  Frontend: [
    ["JavaScript", "javascript"],
    ["TypeScript", "typescript"],
    ["React", "react"],
    ["Next.js", "nextdotjs"],
    ["Vue.js", "vuedotjs"],
    ["Nuxt", "nuxtdotjs"],
    ["Angular", "angular"],
    ["Svelte", "svelte"],
    ["HTML5", "html5"],
    ["CSS3", "css3"],
    ["Tailwind CSS", "tailwindcss"],
    ["Sass", "sass"],
    ["Redux", "redux"],
    ["Vite", "vite"],
  ],
  "Backend / Full-stack": [
    ["Node.js", "nodedotjs"],
    ["Express", "express"],
    ["NestJS", "nestjs"],
    ["Python", "python"],
    ["Django", "django"],
    ["FastAPI", "fastapi"],
    ["Flask", "flask"],
    ["Java", "java"],
    ["Spring", "spring"],
    ["Go", "go"],
    ["Rust", "rust"],
    ["PHP", "php"],
    ["Laravel", "laravel"],
    ["C#", "csharp"],
    ["ASP.NET Core", "dotnet"],
    ["GraphQL", "graphql"],
  ],
  Mobile: [
    ["React Native", "react"],
    ["Flutter", "flutter"],
    ["Swift", "swift"],
    ["Kotlin", "kotlin"],
    ["Android", "android"],
    ["Expo", "expo"],
  ],
  "AI / ML": [
    ["OpenAI", "openai"],
    ["Anthropic", "anthropic"],
    ["TensorFlow", "tensorflow"],
    ["PyTorch", "pytorch"],
    ["scikit-learn", "scikitlearn"],
    ["Hugging Face", "huggingface"],
    ["Pandas", "pandas"],
    ["NumPy", "numpy"],
    ["Jupyter", "jupyter"],
  ],
  "AI Agentics": [
    ["LangChain", "langchain"],
    ["LangGraph", "langchain"],
    ["LlamaIndex", "chainlink"],
    ["CrewAI", "openai"],
    ["AutoGen", "microsoftazure"],
    ["MCP", "json"],
    ["RAG", "elastic"],
    ["Pinecone", "pinecone"],
    ["Weaviate", "weaviate"],
    ["Ollama", "ollama"],
    ["n8n", "n8n"],
  ],
  Database: [
    ["PostgreSQL", "postgresql"],
    ["MySQL", "mysql"],
    ["MongoDB", "mongodb"],
    ["Redis", "redis"],
    ["SQLite", "sqlite"],
    ["Elasticsearch", "elasticsearch"],
    ["Qdrant", "qdrant"],
    ["Supabase", "supabase"],
    ["Firebase", "firebase"],
  ],
  "DevOps / Cloud": [
    ["Git", "git"],
    ["GitHub", "github"],
    ["GitHub Actions", "githubactions"],
    ["GitLab", "gitlab"],
    ["Docker", "docker"],
    ["Kubernetes", "kubernetes"],
    ["Terraform", "terraform"],
    ["Ansible", "ansible"],
    ["Nginx", "nginx"],
    ["Amazon AWS", "amazonaws"],
    ["Google Cloud", "googlecloud"],
    ["Microsoft Azure", "microsoftazure"],
    ["Vercel", "vercel"],
    ["Linux", "linux"],
    ["Prometheus", "prometheus"],
    ["Grafana", "grafana"],
  ],
  "Testing / QA": [
    ["Playwright", "playwright"],
    ["Cypress", "cypress"],
    ["Jest", "jest"],
    ["Vitest", "vitest"],
    ["Selenium", "selenium"],
    ["Postman", "postman"],
    ["JMeter", "apachejmeter"],
    ["Appium", "appium"],
    ["Storybook", "storybook"],
  ],
  Security: [
    ["OWASP", "owasp"],
    ["Auth0", "auth0"],
    ["OAuth", "openid"],
    ["JWT", "jsonwebtokens"],
    ["Cloudflare", "cloudflare"],
  ],
  "Design / Product": [
    ["Figma", "figma"],
    ["Adobe XD", "adobexd"],
    ["Jira", "jira"],
    ["Notion", "notion"],
    ["Miro", "miro"],
    ["Linear", "linear"],
    ["Confluence", "confluence"],
  ],
  "Marketing / Growth": [
    ["Google Analytics", "googleanalytics"],
    ["Google Ads", "googleads"],
    ["Meta Ads", "meta"],
    ["HubSpot", "hubspot"],
    ["Mailchimp", "mailchimp"],
    ["SEO", "googlesearchconsole"],
    ["Hotjar", "hotjar"],
    ["Canva", "canva"],
    ["WordPress", "wordpress"],
    ["Webflow", "webflow"],
  ],
  "HR / People Ops": [
    ["Workday", "workday"],
    ["BambooHR", "bamboohr"],
    ["Greenhouse", "greenhouse"],
    ["Excel", "microsoftexcel"],
    ["Google Sheets", "googlesheets"],
    ["Slack", "slack"],
    ["Microsoft Teams", "microsoftteams"],
    ["Zoom", "zoom"],
  ],
  "CMS / Commerce": [
    ["Strapi", "strapi"],
    ["Contentful", "contentful"],
    ["Shopify", "shopify"],
    ["WooCommerce", "woo"],
    ["Sanity", "sanity"],
    ["Stripe", "stripe"],
    ["PayPal", "paypal"],
  ],
};

export const CATALOG: TechItem[] = Object.entries(TECH_CATEGORIES).flatMap(
  ([category, items]) =>
    items.map(([label, slug]) => ({
      id: `${category}:${label}`,
      label,
      slug,
      category,
    })),
);

export const DEFAULT_SELECTED: string[] = [];

export function slugify(label: string) {
  return label.toLowerCase().replace(/[^a-z0-9]/g, "");
}
